import functions as f
import partition_manager as pmanager
import cmd_manager as cm
import create_base_os as cbos
import acount_manager as am
import second_base_os as sbos
import pakages as pk
import final_configs as fc
import repositorys as rp